server:
  port: 8080


spring:
  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_anbd?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 12345678

  #JPA ??
  jpa:
    show-sql: true  # JPA ?? ???? SQL? ?? ??
    properties:
      hibernate.format_sql: true   # ?? ??? ??

    hibernate:
      ddl-auto: create

  # security
  security:
    user:
      name: user
      password: 1234



