spring:
  mail:
    username: goun3596@gmail.com
    password: xddrqmgsbvzcbjrb
  # security
  security:
    # oauth2 client
    oauth2:
      client:
        registration:
          google:
            client-id: 1095982054826-ujjgn71dm1p319m06816b84kvq802u84.apps.googleusercontent.com    # REST API 키
            client-secret: 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
            scope: profile, email # 기본값이 openid, profile, email이지만 openid를 등록하게 되면 서비스마다(카카오, 네이버) OAuth2Service를 만들어야하기 때문에 profile, email만 scope로 지정
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
          kakao:
            client-id: 4777ab60a5708fb63bc19ab4c4442803 # REST API 키
            client-secret: tJ4OUyoGP8Ry2HMvDOo4EyjnjNf1r9bz
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image  # 동의 항목
            client-name: Kakao
          naver:
            client-id: HYNs4yK_yplbQpmLUSH2 # REST API 키
            client-secret: 15ljuhdoY0
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image  # 동의 항목
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response